baseURL = "https://laughsign.com"
languageCode = 'en-us'
publishDir = "public"
[params]
    title = "Laugh Sign" 
    description = "The replication of a live studio audience's responses"
    favicon = ""
    message = "To you, dear sister, for every cheesy joke, and for filling my life with laughter and warmth. This one's for you. ❤️" 
    release = "Dec 22, 2024" 
    background = "" 

[taxonomies]
tag = ""
category = ""